import {
  Activity,
  AlertTriangle,
  BadgeDollarSign,
  ClipboardList,
  CreditCard,
  FileCog,
  FileText,
  Flag,
  Flame,
  GaugeCircle,
  KeyRound,
  Network,
  Settings2,
  Trash2,
  UserCog,
} from 'lucide-vue-next'
import type { Component } from 'vue'
import type {
  AdminDomainKey,
  AdminModuleCapability,
  AdminModuleRiskLevel,
  AdminModuleStatusSource,
  ControlRoomTabGroup,
  ControlRoomTabId,
} from './types'

export type AdminModuleDescriptor = {
  id: ControlRoomTabId
  group: ControlRoomTabGroup
  label: string
  description: string
  whenToUse: string
  riskLevel: AdminModuleRiskLevel
  riskNote: string
  component: string
  requiredCapability: AdminModuleCapability
  statusBadgeSource?: AdminModuleStatusSource
  domain: AdminDomainKey
  icon: Component
}

export const adminModules: AdminModuleDescriptor[] = [
  {
    id: 'overview',
    group: 'Command',
    label: 'Command Center',
    description: 'Daily operating view for health, readiness, failures, feedback, and configuration attention.',
    whenToUse: 'Start here after deploys, during daily checks, or when you need to know what needs attention first.',
    riskLevel: 'low',
    riskNote: 'Read-only dashboard. Use it to decide where to go next.',
    component: 'OverviewTab',
    requiredCapability: 'admin:overview:read',
    statusBadgeSource: 'systemHealth',
    domain: 'overview',
    icon: GaugeCircle,
  },
  {
    id: 'users',
    group: 'Operate',
    label: 'Users & Access',
    description: 'Manage account state, roles, verification, manual entitlements, bans, and reset links.',
    whenToUse: 'Use when a user cannot sign in, needs entitlement support, or must be blocked for abuse.',
    riskLevel: 'high',
    riskNote: 'Changes can affect login, access level, and subscription visibility for real users.',
    component: 'UsersTab',
    requiredCapability: 'admin:users:manage',
    domain: 'users',
    icon: UserCog,
  },
  {
    id: 'jobs',
    group: 'Operate',
    label: 'Job Center',
    description: 'Observe PDF, OCR, and Office background jobs, status, output paths, and error summaries.',
    whenToUse: 'Use when a customer reports a stuck or failed conversion, or after smoke tests.',
    riskLevel: 'medium',
    riskNote: 'Mostly read-only operational data. Output paths and errors may reveal technical details.',
    component: 'JobsTab',
    requiredCapability: 'admin:operations:observe',
    statusBadgeSource: 'failedJobs',
    domain: 'operations',
    icon: GaugeCircle,
  },
  {
    id: 'feedback',
    group: 'Operate',
    label: 'Feedback Inbox',
    description: 'Review user feedback, diagnostic codes, status, severity, and internal admin notes.',
    whenToUse: 'Use when triaging user-reported problems or closing resolved support reports.',
    riskLevel: 'medium',
    riskNote: 'Status and notes affect support workflow, but do not change product behavior.',
    component: 'FeedbackTab',
    requiredCapability: 'admin:operations:observe',
    statusBadgeSource: 'openFeedback',
    domain: 'operations',
    icon: ClipboardList,
  },
  {
    id: 'flags',
    group: 'Product',
    label: 'Tools & Features',
    description: 'Control tool visibility, enabled state, login requirement, Pro gates, and maintenance copy.',
    whenToUse: 'Use to hide a tool, put it into maintenance, require login, or adjust Pro access.',
    riskLevel: 'high',
    riskNote: 'Changes affect what users can see and whether frontend routes and backend APIs allow access.',
    component: 'FeatureFlagsTab',
    requiredCapability: 'admin:product:configure',
    statusBadgeSource: 'lockedFlags',
    domain: 'productConfig',
    icon: Flag,
  },
  {
    id: 'serviceProviders',
    group: 'Product',
    label: 'Service Providers',
    description: 'Configure runtime readiness for OCR, Office conversion, and AI providers.',
    whenToUse: 'Use when OCR, Office, or AI features are unavailable, slow, or need runtime configuration changes.',
    riskLevel: 'high',
    riskNote: 'Misconfiguration can break conversion features. Env fallback remains the safety path.',
    component: 'ServiceProvidersTab',
    requiredCapability: 'admin:product:configure',
    statusBadgeSource: 'serviceProviderReadiness',
    domain: 'productConfig',
    icon: Network,
  },
  {
    id: 'settings',
    group: 'Product',
    label: 'Site Settings',
    description: 'Manage public site configuration, display switches, and operational site parameters.',
    whenToUse: 'Use when adjusting site-level copy, public config, or operational display values.',
    riskLevel: 'medium',
    riskNote: 'Changes can affect public pages and runtime presentation.',
    component: 'SiteSettingsTab',
    requiredCapability: 'admin:product:configure',
    domain: 'productConfig',
    icon: Settings2,
  },
  {
    id: 'content',
    group: 'Product',
    label: 'Content Blocks',
    description: 'Edit reusable copy blocks for landing, tool, and public content surfaces.',
    whenToUse: 'Use for content updates that should not require a code deploy.',
    riskLevel: 'medium',
    riskNote: 'Changes affect public messaging and conversion quality.',
    component: 'ContentBlocksTab',
    requiredCapability: 'admin:product:configure',
    domain: 'productConfig',
    icon: FileText,
  },
  {
    id: 'plans',
    group: 'Revenue',
    label: 'Plans & Pricing',
    description: 'Manage public plan catalog, display prices, billing intervals, and provider price mappings.',
    whenToUse: 'Use before changing pricing display, hiding a plan, or correcting checkout mapping.',
    riskLevel: 'high',
    riskNote: 'Changes can affect Pricing, checkout mapping, and purchase expectations.',
    component: 'PlansPricingTab',
    requiredCapability: 'admin:revenue:configure',
    domain: 'revenue',
    icon: BadgeDollarSign,
  },
  {
    id: 'paymentSetup',
    group: 'Revenue',
    label: 'Payment Providers',
    description: 'Manage Stripe, PayPal, and GM Pay configuration, readiness, webhooks, and write-only secrets.',
    whenToUse: 'Use when onboarding or repairing a payment channel, rotating keys, or checking provider readiness.',
    riskLevel: 'critical',
    riskNote: 'Bad values can break checkout or payment redirects. Secrets are write-only; blank secret inputs preserve existing values.',
    component: 'PaymentSetupTab',
    requiredCapability: 'admin:revenue:configure',
    statusBadgeSource: 'paymentReadiness',
    domain: 'revenue',
    icon: FileCog,
  },
  {
    id: 'payments',
    group: 'Revenue',
    label: 'Payments & Evidence',
    description: 'Review orders, provider events, mismatch risks, pending expirations, and integration evidence.',
    whenToUse: 'Use during payment support, provider handoff, smoke testing, or reconciliation checks.',
    riskLevel: 'medium',
    riskNote: 'Diagnostic view only in this phase. It does not trigger entitlement automation.',
    component: 'PaymentsTab',
    requiredCapability: 'admin:revenue:reconcile',
    statusBadgeSource: 'paymentRisk',
    domain: 'revenue',
    icon: CreditCard,
  },
  {
    id: 'errors',
    group: 'System',
    label: 'Errors & Diagnostics',
    description: 'Inspect recent API errors, failed jobs, diagnostic summaries, and support signals.',
    whenToUse: 'Use when the dashboard flags errors or when a customer provides a diagnostic code.',
    riskLevel: 'low',
    riskNote: 'Read-only diagnostics. Avoid copying sensitive payloads into public channels.',
    component: 'ErrorsTab',
    requiredCapability: 'admin:operations:observe',
    statusBadgeSource: 'apiErrors',
    domain: 'operations',
    icon: Flame,
  },
  {
    id: 'maintenance',
    group: 'System',
    label: 'Maintenance',
    description: 'Clean test accounts, live-acceptance feedback, expired files, and review retention stats.',
    whenToUse: 'Use after acceptance testing, deploy smoke tests, or when temporary files need cleanup.',
    riskLevel: 'critical',
    riskNote: 'Includes destructive cleanup actions. Review counts before confirming.',
    component: 'MaintenanceTab',
    requiredCapability: 'admin:operations:maintain',
    statusBadgeSource: 'maintenanceRisk',
    domain: 'operations',
    icon: Trash2,
  },
  {
    id: 'security',
    group: 'System',
    label: 'Security',
    description: 'Rotate administrator password and manage security-sensitive admin access workflows.',
    whenToUse: 'Use for admin handoff, credential rotation, or suspected credential exposure.',
    riskLevel: 'critical',
    riskNote: 'Can lock operators out if used incorrectly. Confirm access before rotating credentials.',
    component: 'SecurityTab',
    requiredCapability: 'admin:security:manage',
    domain: 'security',
    icon: KeyRound,
  },
  {
    id: 'audit',
    group: 'System',
    label: 'Audit Logs',
    description: 'Review recent admin actions, changed fields, targets, and operation status.',
    whenToUse: 'Use to confirm who changed a setting, when it changed, and whether it succeeded.',
    riskLevel: 'low',
    riskNote: 'Read-only accountability log. Secrets should never appear here.',
    component: 'AuditLogsTab',
    requiredCapability: 'admin:audit:read',
    statusBadgeSource: 'auditRecent',
    domain: 'security',
    icon: Activity,
  },
]

export const riskLevelLabels: Record<AdminModuleRiskLevel, string> = {
  low: 'Low risk',
  medium: 'Medium risk',
  high: 'High risk',
  critical: 'Critical',
}

export const riskLevelTones: Record<AdminModuleRiskLevel, 'neutral' | 'info' | 'success' | 'warning' | 'danger'> = {
  low: 'neutral',
  medium: 'info',
  high: 'warning',
  critical: 'danger',
}

export const highRiskIcon = AlertTriangle

export const adminModulesById = Object.fromEntries(
  adminModules.map((module) => [module.id, module]),
) as Record<ControlRoomTabId, AdminModuleDescriptor>
