import {
  formatAdminDate,
  formatAdminMoney,
  parseAdminDiagnostics,
} from './formatters'
import { createControlRoomActions } from './actions'
import { createControlRoomClipboard } from './clipboard'
import { createControlRoomContext } from './context'
import { createControlRoomDomains } from './domains'
import { adminModules } from './modules'
import { controlRoomTabs } from './tabs'

export const useControlRoom = () => {
  const ctx = createControlRoomContext()
  const clipboard = createControlRoomClipboard(ctx)
  const actions = createControlRoomActions(ctx)
  const domains = createControlRoomDomains(ctx, actions, clipboard)

  return {
    modules: adminModules,
    tabs: controlRoomTabs,
    domains,
    overviewModule: domains.overview,
    usersModule: domains.users,
    revenueModule: domains.revenue,
    productConfigModule: domains.productConfig,
    operationsModule: domains.operations,
    securityModule: domains.security,
    loading: ctx.loading,
    savingKey: ctx.savingKey,
    activeTab: ctx.activeTab,
    error: ctx.error,
    success: ctx.success,
    overview: ctx.overview,
    operations: ctx.operations,
    settings: ctx.settings,
    flags: ctx.flags,
    contentBlocks: ctx.contentBlocks,
    auditLogs: ctx.auditLogs,
    users: ctx.users,
    userPasswordResetLinks: ctx.userPasswordResetLinks,
    jobs: ctx.jobs,
    feedbackReports: ctx.feedbackReports,
    apiErrors: ctx.apiErrors,
    diagnostics: ctx.diagnostics,
    healthReport: ctx.healthReport,
    maintenance: ctx.maintenance,
    paymentSummary: ctx.paymentSummary,
    pricingPlans: ctx.pricingPlans,
    serviceProviderConfigs: ctx.serviceProviderConfigs,
    userSearch: ctx.userSearch,
    jobStatusFilter: ctx.jobStatusFilter,
    jobSearch: ctx.jobSearch,
    paymentProviderFilter: ctx.paymentProviderFilter,
    paymentStatusFilter: ctx.paymentStatusFilter,
    serviceProviderServiceFilter: ctx.serviceProviderServiceFilter,
    feedbackStatusFilter: ctx.feedbackStatusFilter,
    highlightedFeedbackId: ctx.highlightedFeedbackId,
    copiedFeedbackId: ctx.copiedFeedbackId,
    healthReportCopied: ctx.healthReportCopied,
    diagnosticSummaryCopied: ctx.diagnosticSummaryCopied,
    reconciliationCopied: ctx.reconciliationCopied,
    evidenceCopied: ctx.evidenceCopied,
    selectedContent: ctx.selectedContent,
    pendingConfirmation: ctx.pendingConfirmation,
    enabledFlagCount: ctx.enabledFlagCount,
    lockedFlagCount: ctx.lockedFlagCount,
    filteredJobs: ctx.filteredJobs,
    formatDate: formatAdminDate,
    formatMoney: formatAdminMoney,
    parseDiagnostics: parseAdminDiagnostics,
    buildHealthReportSummary: clipboard.buildHealthReportSummary,
    copyFeedbackSummary: clipboard.copyFeedbackSummary,
    copyHealthReport: clipboard.copyHealthReport,
    copyDiagnosticSummary: clipboard.copyDiagnosticSummary,
    copyReconciliationSummary: clipboard.copyReconciliationSummary,
    copyPaymentEvidencePacket: clipboard.copyPaymentEvidencePacket,
    closeAdminConfirmation: ctx.closeAdminConfirmation,
    confirmAdminAction: ctx.confirmAdminAction,
    loadHealthReport: actions.loadHealthReport,
    loadAdminData: actions.loadAdminData,
    saveFlag: actions.saveFlag,
    saveSetting: actions.saveSetting,
    saveContentBlock: actions.saveContentBlock,
    searchUsers: actions.searchUsers,
    saveUser: actions.saveUser,
    toggleUserBan: actions.toggleUserBan,
    createPasswordResetLink: actions.createPasswordResetLink,
    deleteUser: actions.deleteUser,
    loadJobs: actions.loadJobs,
    loadPayments: actions.loadPayments,
    savePricingPlan: actions.savePricingPlan,
    loadServiceProviders: actions.loadServiceProviders,
    saveServiceProvider: actions.saveServiceProvider,
    validateServiceProvider: actions.validateServiceProvider,
    loadFeedback: actions.loadFeedback,
    saveFeedback: actions.saveFeedback,
    cleanupLiveAcceptanceFeedback: actions.cleanupLiveAcceptanceFeedback,
    refreshMaintenance: actions.refreshMaintenance,
    cleanupTestUsers: actions.cleanupTestUsers,
    cleanupExpiredFiles: actions.cleanupExpiredFiles,
    openFeedbackFromDiagnostics: actions.openFeedbackFromDiagnostics,
    loadDiagnostics: actions.loadDiagnostics,
  }
}
